
services:

    ds.communication.provider.contact_information_exclusion:
        class: Ds\Bundle\CommunicationBundle\Provider\ContactInformationExclusionProvider
        arguments:
            - "@oro_entity_config.provider.entity"
            - "@doctrine"

    ds.communication.provider.chain_exclusion:
        class: %oro_entity.exclusion_provider.chain.class%
        calls:
            - [addProvider,  ["@oro_query_designer.exclusion_provider"]]
            - [addProvider,  ["@ds.communication.provider.contact_information_exclusion"]]

    ds.communication.entity_provider.contact_information:
        parent: oro_query_designer.entity_provider
        calls:
            - [setExclusionProvider,  ["@ds.communication.provider.chain_exclusion"]]


    ds.communication.grid.datagrid_configuration_builder:
        class: Ds\Bundle\CommunicationBundle\Grid\CommunicationDatagridConfigurationBuilder
        parent: oro_report.grid.base_configuration_builder


    ds.communication.datagrid.configuration.provider:
        class: Ds\Bundle\CommunicationBundle\Grid\ConfigurationProvider
        arguments:
            - '@ds.communication.grid.datagrid_configuration_builder'
            - '@doctrine'
        tags:
            - { name: oro_datagrid.configuration.provider, priority: 10 }


    ds.communication.message_event.delivery_status.handler:
        class: Ds\Bundle\CommunicationBundle\Provider\DeliveryStatusUpdateHandler
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: ds.communication.message_event.handler, priority: 10 }


    ds.communication.message_event.click_track.handler:
        class: Ds\Bundle\CommunicationBundle\Provider\TrackClicksHandler
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: ds.communication.message_event.handler, priority: 11 }




